version: '3.7'

services:
  api-nginx:
    image: nginx:latest
    container_name: api-nginx
    depends_on:
      - api-php
    ports:
      - "8005:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - api

  api-php:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api-mysql
    container_name: api-php
    volumes:
      - .:/var/www/html
    ports:
      - "9000"
    networks:
      - api

  api-mysql:
    image: "mysql:latest"
    container_name: api-mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bevi
    ports:
      - "3306"
    networks:
      - api

  # api-redis:
  #   image: "redis:alpine"
  #   container_name: api-redis
  #   command: redis-server --requirepass secret
  #   ports:
  #     - "6379"
  #   networks:
  #     - api

networks:
  api:
    driver: bridge
